In [2]:
import numpy as np
import pandas as pd

from IPython.display import display, HTML
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio


import seaborn as sns
from importlib import reload
import matplotlib.pyplot as plt
import matplotlib
import warnings

# Configure Jupyter Notebook
pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', 500) 
pd.set_option('display.expand_frame_repr', False)
display(HTML("<style>div.output_scroll { height: 35em; }</style>"))

reload(plt)
%matplotlib inline
%config InlineBackend.figure_format ='retina'

warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv("battery_data.csv")

In [6]:
df.head()

   Cycle_Index  Discharge Time (s)  Decrement 3.6-3.4V (s)  Max. Voltage Dischar. (V)  Min. Voltage Charg. (V)  Time at 4.15V (s)  Time constant current (s)  Charging time (s)   RUL
0          1.0             2595.30             1151.488500                      3.670                    3.211           5460.001                    6755.01           10777.82  1112
1          2.0             7408.64             1172.512500                      4.246                    3.220           5508.992                    6762.02           10500.35  1111
2          3.0             7393.76             1112.992000                      4.249                    3.224           5508.993                    6762.02           10420.38  1110
3          4.0             7385.50             1080.320667                      4.250                    3.225           5502.016                    6762.02           10322.81  1109
4          6.0            65022.75            29813.487000                      4.290                    3.398           5480.992                   53213.54           56699.65  1107

In [7]:
df['Battery ID']= 0 
batteries=[] 
ID=1
for rul in df['RUL']: 
    batteries.append(ID) 
    if rul == 0: 
        ID+=1
        continue
df['Battery ID'] = batteries

In [8]:
train_battery_ids = []
test_battery_ids = []
battery_ids = df['Battery ID'].unique()

for i in battery_ids:
    if i<9:
        train_battery_ids.append(i)
    else:
        test_battery_ids.append(i)
df_train = df[df['Battery ID'].isin(train_battery_ids)]
df_test = df[df['Battery ID'].isin(test_battery_ids)]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15064 entries, 0 to 15063
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Cycle_Index                15064 non-null  float64
 1   Discharge Time (s)         15064 non-null  float64
 2   Decrement 3.6-3.4V (s)     15064 non-null  float64
 3   Max. Voltage Dischar. (V)  15064 non-null  float64
 4   Min. Voltage Charg. (V)    15064 non-null  float64
 5   Time at 4.15V (s)          15064 non-null  float64
 6   Time constant current (s)  15064 non-null  float64
 7   Charging time (s)          15064 non-null  float64
 8   RUL                        15064 non-null  int64
 9   Battery ID                 15064 non-null  int64
dtypes: float64(8), int64(2)
memory usage: 1.1 MB

   Cycle_Index  Discharge Time (s)  Decrement 3.6-3.4V (s)  Max. Voltage Dischar. (V)  Min. Voltage Charg. (V)  Time at 4.15V (s)  Time constant current (s)  Charging time (s)   RUL  Battery ID
0          1.0             2595.30             1151.488500                      3.670                    3.211           5460.001                    6755.01           10777.82  1112           1
1          2.0             7408.64             1172.512500                      4.246                    3.220           5508.992                    6762.02           10500.35  1111           1
2          3.0             7393.76             1112.992000                      4.249                    3.224           5508.993                    6762.02           10420.38  1110           1
3          4.0             7385.50             1080.320667                      4.250                    3.225           5502.016                    6762.02           10322.81  1109           1
4          6.0            65022.75            29813.487000                      4.290                    3.398           5480.992                   53213.54           56699.65  1107           1

In [ ]:
df.head()